### ISSUE TITLE
Rank-1 cholesky update failed due to numerical issue 

### ISSUE THREAD

**Issue by LuTaonuwhu** [mherb/kalman#20] opened 2018-07-24 11:23 UTC
In UKF and SR-UKF, the update will fail due to the non-positive definite of covariance P and square-root S. Is there a solution to fix the problem or avoid it?

**Comment by mherb** [comment] 2018-07-29 07:46
Duplicate of #8

**Closed by mherb** 2018-07-29 07:46 UTC
Labels: duplicate
